name: Alex Merced - The Latino Libertarian
favicon: null
layout_spectrum: 0.4656622405163944
typography_spectrum: 0.06139793712645769
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#020204'
    - '#553331'
    - '#f8cd65'
    - '#99722b'
  brandStrength: 0.5
  lightness: 0.013348035048693419
  saturation: 0.840009602252394
  rhythmicContrast: 0.08857432473450899
purpose: []
